version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: mynginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - br3
    depends_on:
      - "tomcat"

  tomcat:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    container_name: mytomcat
    ports:
      - 8080:8080
    networks:
      - br3

networks:
  br3:
    driver: bridge
    ipam:
      config:
        - subnet: 123.45.17.0/24

